### ISSUE TITLE
Collectible assembly generation

### ISSUE THREAD

**Issue by masonwheeler** [Microsoft/cci#21]
I'm working on porting a compiler over from `Reflection.Emit` to CCI.  One of the things that this compiler is able to do is generate assemblies in memory, for use as an interpreter.  With `Reflection.Emit` it's trivial to mark an assembly as collectible, but I don't see any equivalent here.  What's the recommended way to create collectible assemblies with CCI?

**Comment by MichalStrehovsky** [comment]
Whether an assembly is "collectible" depends on how the assembly was loaded. It's not a property of the assembly itself.

The .NET Runtime is not aware of assemblies loaded into the CCI host. You can't create a collectible assembly with CCI because you can't create an assembly with CCI that the runtime would be aware of. CCI's host and type system are separate from the runtime (it's the key difference from `Reflection.Emit`).

The only way to load the assembly into the runtime is to *use CCI to save it into a byte array, or a file on disk*, and then use API such as `Assembly.Load` to load the byte array or file into the runtime. The question is really: "How do I load an assembly as a collectible assembly?". The answer to that is in this open issue: dotnet/coreclr#552 (spoiler: you can't yet).

**Comment by masonwheeler** [comment]
I see.

That's a bit disappointing, but it's good to know at least.  Thanks.
