### ISSUE TITLE
TypeHelper.GetMethod can't find methods with ref arguments

### ISSUE THREAD

**Issue by masonwheeler** [Microsoft/cci#26]
For a compiler to look up a method in an external assembly, the standard technique seems to be `UnitHelper.GetType` followed by `TypeHelper.GetMethod`.  But this approach fails when looking up a method with a **ref** argument, because [the code explicitly prevents matches if any parameter is ByRef, Out, or has modifiers](https://github.com/Microsoft/cci/blob/master/CoreObjectModel/MetadataHelper/TypeHelper.cs#L1282).

What is the correct way to look up such a method?

**Comment by MichalStrehovsky** [comment]
This is because CCI has a weird way to represent ByRef types and types with modifiers in parameters (it's a property of the method *parameter*, not of the method *parameter type*). So if you have a `void Foo(out int x)` method, the type of the parameter `x` is `int` (with `IsByReference == true`), not `ByRef to an int`. Odd behavior of `GetMethod` tries to be consistent with that.

You can either look for it by manually iterating over all the methods, or by constructing a `MethodReference` and resolving it.
